In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import sklearn
from sklearn.preprocessing import StandardScaler

# from thefuzz import process
from difflib import get_close_matches


# import 'Pandas' 
import pandas as pd 

# import 'Numpy' 
import numpy as np

# import subpackage of Matplotlib
import matplotlib.pyplot as plt

# import 'Seaborn' 
import seaborn as sns

# to suppress warnings 
from warnings import filterwarnings
filterwarnings('ignore')

# display all columns of the dataframe
pd.options.display.max_columns = None

# display all rows of the dataframe
pd.options.display.max_rows = None
 
# to display the float values upto 6 decimal places     
pd.options.display.float_format = '{:.6f}'.format

# import train-test split 
from sklearn.model_selection import train_test_split

# # import various functions from statsmodels
# import statsmodels
import statsmodels.api as sm
# import statsmodels.stats.api as sms
# from statsmodels.graphics.gofplots import qqplot

# # import 'stats'
# from scipy import stats

# # 'metrics' from sklearn is used for evaluating the model performance
# from sklearn.metrics import mean_squared_error

# # import functions to perform feature selection
# from mlxtend.feature_selection import SequentialFeatureSelector as sfs
# #from sklearn.feature_selection import SelectFromModel
from sklearn.feature_selection import RFE

# import function to perform linear regression
from sklearn.linear_model import LinearRegression

# import functions to perform cross validation
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold


from geopy.geocoders import Nominatim


from geopy.geocoders import GoogleV3

In [3]:
train = pd.read_csv('train_(2)_(1)_(1)_(1).csv')
test = pd.read_csv('test_(2)_(1)_(1)_(1).csv')
avgRent = pd.read_csv('avg_rent_(1)_(1)_(1)_(1).csv')
disCityCenter = pd.read_csv('dist_from_city_centre_(1)_(1)_(1)_(1).csv')
sampleSubmission = pd.read_csv('sample_submission_(3)_(1)_(1)_(1).csv')

In [4]:
# Replace with your actual Google Cloud API Key
geolocator = GoogleV3(api_key="AIzaSyANkc4LH2IU2xzSHzDLet68SUWZWftyJ-M")

location = geolocator.geocode("bangalore")
print(location.latitude, location.longitude)

12.9628669 77.57750899999999

In [36]:
def geocodeFn(name):
    try:
        location = geolocator.geocode("bangalore " + name)
        return f'{location.latitude}, {location.longitude}'
    except:
        print("Error in geocoding for location:", name)
        return (np.nan, np.nan)

In [22]:
test['coordinates'] = test['location'].apply(lambda x: geocodeFn("bangalore " + x))

In [23]:
test[['latitude', 'longitude']] = test.coordinates.str.split(", ",expand=True)

In [24]:
test.to_csv("test.csv")

In [37]:
train[train.location.isna()]

,ID,area_type,availability,location,size,society,total_sqft,bath,balcony,price
568,568,Super built-up Area,Ready To Move,NaN,3 BHK,Grare S,1600,3.000000,2.000000,86.000000

In [38]:
train.dropna(subset=['location'],inplace=True)

In [39]:
train[train.location.isna()]

Empty DataFrame
Columns: [ID, area_type, availability, location, size, society, total_sqft, bath, balcony, price]
Index: []

In [33]:
train.location.isnan().sum()

AttributeError: 'Series' object has no attribute 'isnan'

In [40]:

train['coordinates'] = train['location'].apply(lambda x: geocodeFn( x))

In [41]:
train[['latitude', 'longitude']] = train.coordinates.str.split(", ",expand=True)

In [42]:
train.to_csv("train.csv")

In [ ]:
# avgRent['coordinates'] = avgRent['location'].apply(lambda x: geocodeFn(x))

In [ ]:
# avgRent.to_csv('avgRent.csv')

In [ ]:


# avgRent[['latitude', 'longitude']] = avgRent.coordinates.str.split(", ",expand=True)

In [ ]:
# avgRent.to_csv('avgRent.csv')

In [12]:
disCityCenter['coordinates'] = disCityCenter['location'].apply(lambda x: geocodeFn("bangalore " + x))

In [17]:
disCityCenter.to_csv("disCityCenter.csv")

<!-- a=[Horamavu Agara, Badavala Nagar, Outer Ring Road East, AMS Layout] -->

In [15]:
disCityCenter[['latitude', 'longitude']] = disCityCenter.coordinates.str.split(", ",expand=True)

In [16]:
# disCityCenter.loc[disCityCenter.location in ['Horamavu Agara', 'Badavala Nagar']]

disCityCenter[
    disCityCenter.location.isin(
        ["Horamavu Agara", "Badavala Nagar", "Outer Ring Road East", "AMS Layout"]
    )
]

,location,dist_from_city,coordinates,latitude,longitude
69,Horamavu Agara,12.200000,"13.0411068, 77.6622027",13.0411068,77.6622027
216,Badavala Nagar,9.600000,"12.9628669, 77.57750899999999",12.9628669,77.57750899999999
280,Outer Ring Road East,9.800000,"13.0277979, 77.632506",13.0277979,77.632506
488,AMS Layout,18.900000,"13.0876909, 77.5583595",13.0876909,77.5583595