# data cleaning

In [64]:
%pip install pandas numpy matplotlib seaborn scikit-learn

Requirement already satisfied: pandas in d:\programfiles\lib\site-packages (2.2.2)
Requirement already satisfied: numpy in d:\programfiles\lib\site-packages (1.26.4)
Requirement already satisfied: matplotlib in d:\programfiles\lib\site-packages (3.9.2)
Requirement already satisfied: seaborn in d:\programfiles\lib\site-packages (0.13.2)
Requirement already satisfied: scikit-learn in d:\programfiles\lib\site-packages (1.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\programfiles\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\programfiles\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in d:\programfiles\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: contourpy>=1.0.1 in d:\programfiles\lib\site-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in d:\programfiles\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in d:\programfiles\lib\site-packages (from matplotlib) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\programfiles\lib\site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: packaging>=20.0 in d:\programfiles\lib\site-packages (from matplotlib) (24.1)
Requirement already satisfied: pillow>=8 in d:\programfiles\lib\site-packages (from matplotlib) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in d:\programfiles\lib\site-packages (from matplotlib) (3.1.2)
Requirement already satisfied: scipy>=1.6.0 in d:\programfiles\lib\site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in d:\programfiles\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in d:\programfiles\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: six>=1.5 in d:\programfiles\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [65]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import sklearn
from sklearn.preprocessing import StandardScaler

# from thefuzz import process
from difflib import get_close_matches

In [66]:
# import 'Pandas' 
import pandas as pd 

# import 'Numpy' 
import numpy as np

# import subpackage of Matplotlib
import matplotlib.pyplot as plt

# import 'Seaborn' 
import seaborn as sns

# to suppress warnings 
from warnings import filterwarnings
filterwarnings('ignore')

# display all columns of the dataframe
pd.options.display.max_columns = None

# display all rows of the dataframe
pd.options.display.max_rows = None
 
# to display the float values upto 6 decimal places     
pd.options.display.float_format = '{:.6f}'.format

# import train-test split 
from sklearn.model_selection import train_test_split

# # import various functions from statsmodels
# import statsmodels
import statsmodels.api as sm
# import statsmodels.stats.api as sms
# from statsmodels.graphics.gofplots import qqplot

# # import 'stats'
# from scipy import stats

# # 'metrics' from sklearn is used for evaluating the model performance
# from sklearn.metrics import mean_squared_error

# # import functions to perform feature selection
# from mlxtend.feature_selection import SequentialFeatureSelector as sfs
# #from sklearn.feature_selection import SelectFromModel
from sklearn.feature_selection import RFE

# import function to perform linear regression
from sklearn.linear_model import LinearRegression

# import functions to perform cross validation
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold

In [67]:
train = pd.read_csv('train_(2)_(1)_(1)_(1).csv')
test = pd.read_csv('test_(2)_(1)_(1)_(1).csv')
avgRent = pd.read_csv('avg_rent_(1)_(1)_(1)_(1).csv')
disCityCenter = pd.read_csv('dist_from_city_centre_(1)_(1)_(1)_(1).csv')
sampleSubmission = pd.read_csv('sample_submission_(3)_(1)_(1)_(1).csv')

In [68]:
test.head()

,ID,area_type,availability,location,size,society,total_sqft,bath,balcony
0,0,Super built-up Area,Ready To Move,Chamrajpet,2 BHK,NaN,650,1.000000,1.000000
1,1,Super built-up Area,Ready To Move,7th Phase JP Nagar,3 BHK,SrncyRe,1370,2.000000,1.000000
2,2,Super built-up Area,Ready To Move,Whitefield,3 BHK,AjhalNa,1725,3.000000,2.000000
3,3,Built-up Area,Ready To Move,Jalahalli,2 BHK,NaN,1000,2.000000,0.000000
4,4,Plot Area,Ready To Move,TC Palaya,1 Bedroom,NaN,1350,1.000000,0.000000

In [69]:
print(test.info())
# test.dropna(subset=['size', 'location', 'bath', 'balcony'], inplace=True)
# test['size'].fillna(test['size'].mode(), inplace=True)

test['size'].fillna('2 BHK', inplace=True)
test['bath'].fillna(test['bath'].median(), inplace=True)
test['balcony'].fillna(test['balcony'].median(), inplace=True)
print(test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2664 entries, 0 to 2663
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            2664 non-null   int64
 1   area_type     2664 non-null   object
 2   availability  2664 non-null   object
 3   location      2664 non-null   object
 4   size          2662 non-null   object
 5   society       1590 non-null   object
 6   total_sqft    2664 non-null   object
 7   bath          2656 non-null   float64
 8   balcony       2559 non-null   float64
dtypes: float64(2), int64(1), object(6)
memory usage: 187.4+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2664 entries, 0 to 2663
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            2664 non-null   int64
 1   area_type     2664 non-null   object
 2   availability  2664 non-null   object
 3   location      2664 non-null   object
 4   size          2664 non-null   object
 5   society       1590 non-null   object
 6   total_sqft    2664 non-null   object
 7   bath          2664 non-null   float64
 8   balcony       2664 non-null   float64
dtypes: float64(2), int64(1), object(6)
memory usage: 187.4+ KB
None

In [70]:



print(train.info())
train.dropna(subset=['size', 'location', 'bath', 'balcony'], inplace=True)
print(train.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10656 entries, 0 to 10655
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            10656 non-null  int64
 1   area_type     10656 non-null  object
 2   availability  10656 non-null  object
 3   location      10655 non-null  object
 4   size          10642 non-null  object
 5   society       6228 non-null   object
 6   total_sqft    10656 non-null  object
 7   bath          10591 non-null  float64
 8   balcony       10152 non-null  float64
 9   price         10656 non-null  float64
dtypes: float64(3), int64(1), object(6)
memory usage: 832.6+ KB
None
<class 'pandas.core.frame.DataFrame'>
Index: 10151 entries, 0 to 10655
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            10151 non-null  int64
 1   area_type     10151 non-null  object
 2   availability  10151 non-null  object
 3   location      10151 non-null  object
 4   size          10151 non-null  object
 5   society       5959 non-null   object
 6   total_sqft    10151 non-null  object
 7   bath          10151 non-null  float64
 8   balcony       10151 non-null  float64
 9   price         10151 non-null  float64
dtypes: float64(3), int64(1), object(6)
memory usage: 872.4+ KB
None

### cleaning total_sqft and making it numeric 
as it is expected to be in sq feet

then scaling it

In [71]:
def is_number(x):
    try:
        float(x)
        return True
    except ValueError:
        return False

def return_sqft(x):
    if is_number(x):
        return float(x)
    
    tokens = x.split('-')
    if len(tokens) == 2:
        return (float(tokens[0]) + float(tokens[1])) / 2
    if x.endswith('Sq. Meter') or x.endswith('Sq. Meter'):
        x = float(x.split('Sq')[0])
        return x*10.7639
    if x.endswith('Acres'):
        x = float(x.split('Acr')[0])
        return x*43560
    if x.endswith('Sq. Yards'):
        x = float(x.split('Sq')[0])
        return x*10.7639
    if x.endswith('Grounds'):
        x = float(x.split('Gro')[0])
        return x*2400
    if x.endswith('Cents'):
        x = float(x.split('Cen')[0])
        return x*435.6
    if x.endswith('Perch'):
        x = float(x.split('Per')[0])
        return x*272.25
    if x.endswith('Guntha'):
        x = float(x.split('Gun')[0])
        return x*1089
    
    print("Couldn't parse the value: ", x)
    return x



train['total_sqft'] = train.total_sqft.apply(lambda x: return_sqft(x))
train[train.total_sqft.apply(lambda x: is_number(x) == False)]


# train['price_per_sqft'] = train.price / train.total_sqft
# train.total_sqft.describe()


test['total_sqft'] = test.total_sqft.apply(lambda x: return_sqft(x))
test[test.total_sqft.apply(lambda x: is_number(x) == False)]

Empty DataFrame
Columns: [ID, area_type, availability, location, size, society, total_sqft, bath, balcony]
Index: []

outlier treatment for total_sqft based on area_type


OUTLIERS HAVE NOT YET BEEN TREATED AND MUST BE TREATED FOR ALL CATEGORIES

In [72]:
# # FOR SOME REASON THE R^2 IS REDUCING
# # ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ HENCE THE CODE IS COMMENTED OUT ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

# # TODO: outlier analysis to be done wrt area type 

# # plt.subplots = plt.subplots(figsize=(10,5))


# print(train.area_type.value_counts())
# plt.figure(figsize=(20,10))


# plt.subplot(2,4,1)
# plt.title('Price per sqft distribution for Super built-up  Area')
# sns.boxplot(train[train.area_type == 'Super built-up  Area'].price_per_sqft)
# plt.subplot(2,4,5)
# plt.title('Price per sqft distribution for Super built-up  Area')
# sns.histplot(train[train.area_type == 'Super built-up  Area'].price_per_sqft)



# plt.subplot(2,4,2)
# plt.title('Price per sqft distribution for Built-up  Area')
# sns.boxplot(train[train.area_type == 'Built-up  Area'].price_per_sqft)
# plt.subplot(2,4,6)
# plt.title('Price per sqft distribution for Built-up  Area')
# sns.histplot(train[train.area_type == 'Built-up  Area'].price_per_sqft)



# plt.subplot(2,4,3)
# plt.title('Price per sqft distribution for Plot  Area')
# sns.boxplot(train[train.area_type == 'Plot  Area'].price_per_sqft)
# plt.subplot(2,4,7)
# plt.title('Price per sqft distribution for Plot  Area')
# sns.histplot(train[train.area_type == 'Plot  Area'].price_per_sqft)



# plt.subplot(2,4,4)
# plt.title('Price per sqft distribution for Carpet  Area')
# sns.boxplot(train[train.area_type == 'Carpet  Area'].price_per_sqft)
# plt.subplot(2,4,8)
# plt.title('Price per sqft distribution for Carpet  Area')
# sns.histplot(train[train.area_type == 'Carpet  Area'].price_per_sqft)



# plt.tight_layout()
# plt.show()

train['price_per_sqft'] = train.price / train.total_sqft
for i in train.area_type.unique():
    col = train[train.area_type == i].price_per_sqft
    iqr = (col.quantile(0.75) - col.quantile(0.25)) * (3/2)
    train.drop(train[(train.area_type == i) & (train.price_per_sqft > iqr)].index, inplace=True)



# for i in test.area_type.unique():
#     col = test[test.area_type == i].price_per_sqft
#     iqr = (col.quantile(0.75) - col.quantile(0.25)) * (3/2)
#     test.drop(test[(test.area_type == i) & (test.price_per_sqft > iqr)].index, inplace=True)

In [73]:
# print(train.price_per_sqft.describe())
# print(train[train.price_per_sqft > .6])
# train.drop(train[train.price_per_sqft > 0.6].index, inplace=True, axis=0)

In [74]:
# scaling data => total sq feet

# note that we must do outlier treatment before scaling
# min max scaling for total_sqft

# train.total_sqft = train.total_sqft.apply(lambda x: (x - train.total_sqft.min())/(train.total_sqft.max() - train.total_sqft.min()))

# all cols are being scaled later

successfully cleaned all non numeric data from total_sqft col

## handling size
- currently 1rk = 0
- 1bhk/1bedroom = 1
- 2bhk/2bedroom = 2 
and soo on

In [75]:
# print(train['size'].value_counts(dropna=False))
# train[train['size'].apply(lambda x: is_number(x) == False)]

def returnSize(x):
    try:
        if x == '1 RK':
            return 0
        else:
            return int(x.split(' ')[0])
    except:
        print("Couldn't parse size: ", x)


train['size'] = train['size'].apply(lambda x: returnSize(x))
test['size'] = test['size'].apply(lambda x: returnSize(x))

# train.info()

## avilibility

In [76]:
from datetime import datetime

# train.availability.value_counts()

def noOfDays(x):
    if x == 'Ready To Move':
        return 0
    tokens = x.split('-')
    if len(tokens) == 2:
        now = datetime.now()

        date = datetime.strptime(f'{x}-{now.year}', '%d-%b-%Y')

        if (date - now).days < 0:
            date = datetime.strptime(f'{x}-{now.year + 1}', '%d-%b-%Y')
            
        return (date - now).days
    else:
        print("Couldn't parse availability: ", x)
        return -1


train.availability = train.availability.apply(lambda x: noOfDays(x))
test.availability = test.availability.apply(lambda x: noOfDays(x))

# train.info()

Couldn't parse availability:  Immediate Possession
Couldn't parse availability:  Immediate Possession

## encoding area type

n-1 dummy encoding performed 

with value counts

- area_type
- Super built-up  Area    6745
- Built-up  Area          1845
- Plot  Area              1496
- Carpet  Area              65

model performance to be tested including only Super built-up  Area

In [77]:
temp = True
for i in train.area_type.unique():
    if temp:
        temp = False
        continue
    train["area_type_" + i.split("  ")[0].replace(" ", "_").replace("-", "_")] = train.area_type.apply(lambda x: 1 if x==i else 0)

train.drop('area_type', axis=1, inplace=True)

In [78]:
temp = True
for i in test.area_type.unique():
    if temp:
        temp = False
        continue
    test["area_type_" + i.split("  ")[0].replace(" ", "_").replace("-", "_")] = test.area_type.apply(lambda x: 1 if x==i else 0)

test.drop('area_type', axis=1, inplace=True)

# using average rent and distance from city center

In [81]:

# # Function to find the best match and its score using thefuzz.process.extractOne
# def find_closest_match(target, choices):
#     # process.extractOne returns a tuple: (closest_match, score, index)
#     match, score, _ = process.extractOne(target, choices)
#     return match, score

# # Apply the function across rows
# # The result will be a new DataFrame or Series containing the match and score
# train[['avgRentPlace', 'avgRentScore']] = train['location'].apply(
#     lambda x: pd.Series(find_closest_match(x, avgRent['location']))
# )


# train['average_rent'] = train.apply(
#     lambda row: avgRent.loc[avgRent['location'] == row['avgRentPlace'], 'avg_2bhk_rent'].values[0],
#     axis=1
# )

# # train.drop(['avgRentPlace', 'avgRentScore'], axis=1, inplace=True)


# train[['distanceField', 'distanceScore']] = train['location'].apply(
#     lambda x: pd.Series(find_closest_match(x, disCityCenter['location']))
# )

# train["distance_from_city_center"] = train.apply(
#     lambda row: disCityCenter.loc[
#         disCityCenter["location"] == row["distanceField"], "dist_from_city"
#     ].values[0],
#     axis=1,
# )

# # train.drop(['distanceField', 'distanceScore'], axis=1, inplace=True)

In [97]:

%pip install geopy

Collecting geopy
  Using cached geopy-2.4.1-py3-none-any.whl.metadata (6.8 kB)
Collecting geographiclib<3,>=1.52 (from geopy)
  Using cached geographiclib-2.1-py3-none-any.whl.metadata (1.6 kB)
Using cached geopy-2.4.1-py3-none-any.whl (125 kB)
Using cached geographiclib-2.1-py3-none-any.whl (40 kB)
Installing collected packages: geographiclib, geopy
Successfully installed geographiclib-2.1 geopy-2.4.1
Note: you may need to restart the kernel to use updated packages.

In [99]:
# importing geopy library
from geopy.geocoders import Nominatim

# calling the Nominatim tool
loc = Nominatim(user_agent="GetLoc")

# entering the location name
getLoc = loc.geocode("Narayanapura on Hennur Main Road")

# printing address
print(getLoc.address)

# printing latitude and longitude
print("Latitude = ", getLoc.latitude, "\n")
print("Longitude = ", getLoc.longitude)

AttributeError: 'NoneType' object has no attribute 'address'

In [83]:

# I dont want to scale the target variable
y = train['price']

# standard scaling

In [84]:
scaler = StandardScaler()

numeric_cols = train.select_dtypes(include=[np.number]).columns
train[numeric_cols] = scaler.fit_transform(train[numeric_cols])

In [85]:
numeric_cols = test.select_dtypes(include=[np.number]).columns
test[numeric_cols] = scaler.fit_transform(test[numeric_cols])

In [86]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2664 entries, 0 to 2663
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  2664 non-null   float64
 1   availability        2664 non-null   float64
 2   location            2664 non-null   object
 3   size                2664 non-null   float64
 4   society             1590 non-null   object
 5   total_sqft          2664 non-null   float64
 6   bath                2664 non-null   float64
 7   balcony             2664 non-null   float64
 8   area_type_Built_up  2664 non-null   float64
 9   area_type_Plot      2664 non-null   float64
 10  area_type_Carpet    2664 non-null   float64
dtypes: float64(9), object(2)
memory usage: 229.1+ KB

In [87]:
test.head()

,ID,availability,location,size,society,total_sqft,bath,balcony,area_type_Built_up,area_type_Plot,area_type_Carpet
0,-1.731401,-0.425140,Chamrajpet,-0.661886,NaN,-0.196237,-1.311147,-0.774311,-0.475347,-0.404127,-0.082479
1,-1.730100,-0.425140,7th Phase JP Nagar,0.153308,SrncyRe,-0.057916,-0.539236,-0.774311,-0.475347,-0.404127,-0.082479
2,-1.728800,-0.425140,Whitefield,0.153308,AjhalNa,0.010284,0.232674,0.493522,-0.475347,-0.404127,-0.082479
3,-1.727500,-0.425140,Jalahalli,-0.661886,NaN,-0.128998,-0.539236,-2.042145,2.103726,-0.404127,-0.082479
4,-1.726199,-0.425140,TC Palaya,-1.477080,NaN,-0.061759,-1.311147,-2.042145,-0.475347,2.474469,-0.082479

In [88]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2122 entries, 1 to 10651
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        2122 non-null   float64
 1   availability              2122 non-null   float64
 2   location                  2122 non-null   object
 3   size                      2122 non-null   float64
 4   society                   831 non-null    object
 5   total_sqft                2122 non-null   float64
 6   bath                      2122 non-null   float64
 7   balcony                   2122 non-null   float64
 8   price                     2122 non-null   float64
 9   price_per_sqft            2122 non-null   float64
 10  area_type_Super_built_up  2122 non-null   float64
 11  area_type_Built_up        2122 non-null   float64
 12  area_type_Carpet          2122 non-null   float64
dtypes: float64(11), object(2)
memory usage: 232.1+ KB

In [89]:
test.head()

,ID,availability,location,size,society,total_sqft,bath,balcony,area_type_Built_up,area_type_Plot,area_type_Carpet
0,-1.731401,-0.425140,Chamrajpet,-0.661886,NaN,-0.196237,-1.311147,-0.774311,-0.475347,-0.404127,-0.082479
1,-1.730100,-0.425140,7th Phase JP Nagar,0.153308,SrncyRe,-0.057916,-0.539236,-0.774311,-0.475347,-0.404127,-0.082479
2,-1.728800,-0.425140,Whitefield,0.153308,AjhalNa,0.010284,0.232674,0.493522,-0.475347,-0.404127,-0.082479
3,-1.727500,-0.425140,Jalahalli,-0.661886,NaN,-0.128998,-0.539236,-2.042145,2.103726,-0.404127,-0.082479
4,-1.726199,-0.425140,TC Palaya,-1.477080,NaN,-0.061759,-1.311147,-2.042145,-0.475347,2.474469,-0.082479

In [90]:
train.drop(['price_per_sqft'], axis=1, inplace=True)

x = train.drop('price', axis=1)
# y = train['price']

x = x.select_dtypes(include= 'number')
x = sm.add_constant(x)

X_train, X_test, y_train, y_test = train_test_split(x, y, random_state=1, test_size = 0.2)

In [91]:
X_train.head()

,const,ID,availability,size,total_sqft,bath,balcony,area_type_Super_built_up,area_type_Built_up,area_type_Carpet
717,1.000000,-1.517631,-0.465037,-0.602064,-0.054573,-0.472621,0.712635,1.291968,-0.442907,-0.072186
7911,1.000000,0.824880,-0.465037,-0.602064,-0.059114,-0.472621,-0.451500,-0.774013,-0.442907,13.853126
1211,1.000000,-1.356775,-0.465037,1.404605,-0.043222,1.550720,-0.451500,-0.774013,-0.442907,-0.072186
3826,1.000000,-0.505278,0.802950,0.066826,-0.052019,0.201826,0.712635,1.291968,-0.442907,-0.072186
9341,1.000000,1.290517,-0.465037,0.066826,-0.052019,-0.472621,0.712635,-0.774013,2.257809,-0.072186

In [92]:
myModel = sm.OLS(y_train, X_train).fit()
myModel.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.389
Model:                            OLS   Adj. R-squared:                  0.386
Method:                 Least Squares   F-statistic:                     119.4
Date:                Fri, 16 Jan 2026   Prob (F-statistic):          1.43e-173
Time:                        21:32:04   Log-Likelihood:                -9538.7
No. Observations:                1697   AIC:                         1.910e+04
Df Residuals:                    1687   BIC:                         1.915e+04
Df Model:                           9
Covariance Type:            nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
const                       80.6764      1.628     49.570      0.000      77.484      83.869
ID                           0.6409      1.613      0.397      0.691      -2.524       3.805
availability                -2.5492      1.638     -1.556      0.120      -5.762       0.664
size                       -10.2411      3.719     -2.753      0.006     -17.536      -2.946
total_sqft                   1.1710      1.598      0.733      0.464      -1.964       4.306
bath                        31.2200      3.790      8.237      0.000      23.786      38.654
balcony                     14.0089      1.747      8.019      0.000      10.582      17.435
area_type_Super_built_up   -37.5803      1.993    -18.855      0.000     -41.489     -33.671
area_type_Built_up         -26.0012      1.842    -14.116      0.000     -29.614     -22.388
area_type_Carpet            -6.1927      1.626     -3.808      0.000      -9.383      -3.003
==============================================================================
Omnibus:                     1872.587   Durbin-Watson:                   1.927
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           255056.891
Skew:                           5.268   Prob(JB):                         0.00
Kurtosis:                      62.128   Cond. No.                         4.74
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [93]:
test = test.select_dtypes(include= 'number')
test = sm.add_constant(test)

In [94]:
with open('submit.csv', 'w') as f:
    f.write('ID,price\n')
    predictions = myModel.predict(test)
    for idx, pred in enumerate(predictions):
        f.write(f'{idx},{pred}\n')

In [95]:
for i in (myModel.predict(test)):
    print(type(i))
    print(i)

<class 'float'>
64.30011327325843
<class 'float'>
80.21348381143184
<class 'float'>
122.15412315941113
<class 'float'>
-26.20283605248699
<class 'float'>
-19.798389064322855
<class 'float'>
63.392099367688274
<class 'float'>
122.1556570852745
<class 'float'>
79.07462013703645
<class 'float'>
88.43957886313022
<class 'float'>
164.16432657207335
<class 'float'>
80.2311076532563
<class 'float'>
95.17084480791122
<class 'float'>
88.46158419035075
<class 'float'>
72.67068422097971
<class 'float'>
104.340244379092
<class 'float'>
112.95891490714844
<class 'float'>
106.28362331821361
<class 'float'>
88.47699922494843
<class 'float'>
69.20119212896034
<class 'float'>
-8.393742062483057
<class 'float'>
88.52381664160426
<class 'float'>
106.30128795735604
<class 'float'>
88.50861141226827
<class 'float'>
122.13338133202105
<class 'float'>
122.1038450730418
<class 'float'>
119.71296712692241
<class 'float'>
70.15701607630633
<class 'float'>
3.625348760503123
<class 'float'>
39.49218168318569
<class 'float'>
9.34848738829168
<class 'float'>
87.25643365347733
<class 'float'>
139.9648280016539
<class 'float'>
106.31045538347873
<class 'float'>
-24.282688660947468
<class 'float'>
-16.719606500535154
<class 'float'>
56.99324141223989
<class 'float'>
106.26722217890166
<class 'float'>
88.55935572515077
<class 'float'>
-4.1207199795165055
<class 'float'>
237.2351447869495
<class 'float'>
-8.450477562589043
<class 'float'>
138.3580924709267
<class 'float'>
28.54889034496336
<class 'float'>
139.96605537242687
<class 'float'>
88.49770140543194
<class 'float'>
86.81178398178037
<class 'float'>
88.54998431243828
<class 'float'>
66.8008871563011
<class 'float'>
-24.228120020338903
<class 'float'>
38.05433864895754
<class 'float'>
52.43007459991493
<class 'float'>
72.13886129821302
<class 'float'>
88.54373670396329
<class 'float'>
64.32178755367484
<class 'float'>
80.24865571911671
<class 'float'>
88.59572821107204
<class 'float'>
146.2891827721731
<class 'float'>
145.50445111982356
<class 'float'>
137.45675355795674
<class 'float'>
140.04687794676585
<class 'float'>
124.0496892406417
<class 'float'>
69.1920363401814
<class 'float'>
69.71387815511906
<class 'float'>
80.27631054760619
<class 'float'>
122.13268195894389
<class 'float'>
-8.446514537304893
<class 'float'>
88.54865552357612
<class 'float'>
95.14617069737527
<class 'float'>
25.283403996255732
<class 'float'>
64.52955210000714
<class 'float'>
96.46437341356112
<class 'float'>
86.0989577426094
<class 'float'>
122.18434126883709
<class 'float'>
63.48787558624966
<class 'float'>
122.23549937357105
<class 'float'>
155.88703958740632
<class 'float'>
122.20229730787709
<class 'float'>
122.24474839432966
<class 'float'>
-8.358968791456832
<class 'float'>
86.10652480342561
<class 'float'>
122.21800374237235
<class 'float'>
59.247741810311105
<class 'float'>
102.11966165901404
<class 'float'>
-17.620715923063816
<class 'float'>
88.61517271039698
<class 'float'>
122.17065481017164
<class 'float'>
9.433109798642981
<class 'float'>
29.712112241319847
<class 'float'>
72.70641910500647
<class 'float'>
106.37955552247126
<class 'float'>
88.58103000556716
<class 'float'>
7.443823771615748
<class 'float'>
106.33683867824627
<class 'float'>
56.646681172970816
<class 'float'>
106.39137118979735
<class 'float'>
106.34833730354961
<class 'float'>
72.69846389446396
<class 'float'>
88.60238609354943
<class 'float'>
79.00645896536994
<class 'float'>
64.40961536289954
<class 'float'>
162.581454305536
<class 'float'>
118.80920189656432
<class 'float'>
68.83298534302811
<class 'float'>
23.49548903678019
<class 'float'>
41.524691101088884
<class 'float'>
124.11328776022626
<class 'float'>
122.2367477182087
<class 'float'>
58.50180639152339
<class 'float'>
106.34454910488104
<class 'float'>
42.03321945189459
<class 'float'>
77.76002577474452
<class 'float'>
79.35154616958843
<class 'float'>
106.48960780069912
<class 'float'>
98.0706400448802
<class 'float'>
50.774907087783596
<class 'float'>
-17.562327622989645
<class 'float'>
124.08173734408906
<class 'float'>
146.4270800129169
<class 'float'>
-0.6740746380013367
<class 'float'>
72.73990323407708
<class 'float'>
88.60400743272058
<class 'float'>
112.97523603398854
<class 'float'>
122.27977693619597
<class 'float'>
106.40879104503202
<class 'float'>
72.74631985049577
<class 'float'>
69.47224834305327
<class 'float'>
140.14523343177243
<class 'float'>
-10.052880591347687
<class 'float'>
85.24151131147681
<class 'float'>
-8.318939835341794
<class 'float'>
79.86083265747823
<class 'float'>
124.08861436834906
<class 'float'>
-3.9748920199439484
<class 'float'>
88.613491900866
<class 'float'>
106.38241471934774
<class 'float'>
72.34657029835411
<class 'float'>
28.016596765705238
<class 'float'>
88.59320466264533
<class 'float'>
5.047035742566359
<class 'float'>
106.37128442031742
<class 'float'>
-4.707717716386234
<class 'float'>
64.4198726126485
<class 'float'>
9.436362963917624
<class 'float'>
93.46066184212995
<class 'float'>
16.057496904905
<class 'float'>
88.62124312481872
<class 'float'>
-3.92993023943468
<class 'float'>
106.41304547021376
<class 'float'>
76.94815890256244
<class 'float'>
122.24626364715114
<class 'float'>
-8.274443130934273
<class 'float'>
-12.452532983598715
<class 'float'>
83.61069145624975
<class 'float'>
27.577484715251806
<class 'float'>
78.81692102115997
<class 'float'>
88.6711948326444
<class 'float'>
118.09091390518316
<class 'float'>
104.54355612866034
<class 'float'>
88.65569820341081
<class 'float'>
140.1864582978634
<class 'float'>
88.62249613771685
<class 'float'>
106.43371152163978
<class 'float'>
93.87833803667732
<class 'float'>
139.9358115542609
<class 'float'>
1.0686407261404507
<class 'float'>
106.45256740249768
<class 'float'>
162.7203691117911
<class 'float'>
88.6879444747761
<class 'float'>
106.43504612917383
<class 'float'>
88.58500466819505
<class 'float'>
98.16696039886416
<class 'float'>
-8.24569365833996
<class 'float'>
80.34294791116133
<class 'float'>
102.81224379040457
<class 'float'>
9.528945253071889
<class 'float'>
43.19645765917483
<class 'float'>
106.33148272547966
<class 'float'>
63.940373394206105
<class 'float'>
98.17677706422513
<class 'float'>
39.05562430559277
<class 'float'>
80.32037027107798
<class 'float'>
88.64067246895085
<class 'float'>
-24.099572068031517
<class 'float'>
140.1277237957923
<class 'float'>
63.947571830731114
<class 'float'>
113.01755072370581
<class 'float'>
98.82888080839028
<class 'float'>
106.4115126947618
<class 'float'>
-3.9957096232980804
<class 'float'>
80.34541780790009
<class 'float'>
34.976653449399564
<class 'float'>
122.30646211779344
<class 'float'>
98.06831581478282
<class 'float'>
-8.241081393817538
<class 'float'>
88.64745741164258
<class 'float'>
82.79852456630793
<class 'float'>
78.64383235281275
<class 'float'>
11.829844742994391
<class 'float'>
96.83289517144755
<class 'float'>
86.17529576468418
<class 'float'>
80.34333721129906
<class 'float'>
1.2142064457896349
<class 'float'>
98.26111741119978
<class 'float'>
146.4679330348858
<class 'float'>
140.01249857752293
<class 'float'>
106.51514835657095
<class 'float'>
88.6464351778708
<class 'float'>
98.16630182310496
<class 'float'>
98.06686722169567
<class 'float'>
98.14209817558996
<class 'float'>
88.64841902464312
<class 'float'>
9.529186519130583
<class 'float'>
82.30044922507597
<class 'float'>
-8.25230844267658
<class 'float'>
66.6778090673707
<class 'float'>
104.85757176313248
<class 'float'>
86.14736382061312
<class 'float'>
104.49075334345288
<class 'float'>
72.83523281508629
<class 'float'>
140.1005863258482
<class 'float'>
-17.514188453169783
<class 'float'>
88.7817646216357
<class 'float'>
98.12031314056344
<class 'float'>
106.48088325978725
<class 'float'>
88.70687843242087
<class 'float'>
-1.5401039646650296
<class 'float'>
106.41011071766448
<class 'float'>
122.35851072782435
<class 'float'>
13.821013198704728
<class 'float'>
29.932348936815664
<class 'float'>
72.54209598050545
<class 'float'>
138.271456987214
<class 'float'>
88.68497567370092
<class 'float'>
106.49821570171412
<class 'float'>
88.71791198162245
<class 'float'>
103.1174464994076
<class 'float'>
72.79309410239598
<class 'float'>
104.50089753776892
<class 'float'>
122.34315746440933
<class 'float'>
45.822362252096354
<class 'float'>
140.10773959481295
<class 'float'>
125.38825220049905
<class 'float'>
87.02400924850414
<class 'float'>
4.793899122472674
<class 'float'>
122.36480495228918
<class 'float'>
106.46772364840619
<class 'float'>
-8.246852288847023
<class 'float'>
106.45454306316046
<class 'float'>
140.07346401109692
<class 'float'>
98.1653110501302
<class 'float'>
140.13811974309934
<class 'float'>
-4.697032669286052
<class 'float'>
179.4676281055142
<class 'float'>
106.48991313876326
<class 'float'>
154.28707262715173
<class 'float'>
88.71854139740744
<class 'float'>
104.6888269305629
<class 'float'>
104.75759839018896
<class 'float'>
25.50158992835596
<class 'float'>
9.575038804936817
<class 'float'>
140.14690368775618
<class 'float'>
97.84588294035431
<class 'float'>
140.12607444705833
<class 'float'>
23.253374418228635
<class 'float'>
86.21166286368626
<class 'float'>
122.43517210896125
<class 'float'>
-25.78047334943223
<class 'float'>
72.78412506448244
<class 'float'>
146.5034324715257
<class 'float'>
79.39822087246961
<class 'float'>
138.53521902703054
<class 'float'>
106.48759242651492
<class 'float'>
114.04752514056462
<class 'float'>
98.21590732893368
<class 'float'>
98.20796727358398
<class 'float'>
106.4994745332841
<class 'float'>
72.7945823512195
<class 'float'>
79.17813403590475
<class 'float'>
44.07493896868445
<class 'float'>
46.86493975808312
<class 'float'>
88.78661815221682
<class 'float'>
-9.986414278211816
<class 'float'>
113.02302900181147
<class 'float'>
88.74525107071865
<class 'float'>
104.7747012034009
<class 'float'>
71.20313078698692
<class 'float'>
71.01745521808779
<class 'float'>
140.09066939280945
<class 'float'>
140.08025477246053
<class 'float'>
81.24985650603466
<class 'float'>
-25.76047169243728
<class 'float'>
25.579483348526285
<class 'float'>
9.628411535569434
<class 'float'>
43.23855902578139
<class 'float'>
64.55188238508079
<class 'float'>
106.51929202714254
<class 'float'>
9.608124297348773
<class 'float'>
106.52118379234659
<class 'float'>
116.01765455031541
<class 'float'>
-24.035808058352313
<class 'float'>
153.13333915157887
<class 'float'>
88.7512538952859
<class 'float'>
106.54672204739562
<class 'float'>
88.82040883637782
<class 'float'>
122.37769061978825
<class 'float'>
-8.176760226468318
<class 'float'>
106.55500478689322
<class 'float'>
101.50349121081537
<class 'float'>
17.222666449324997
<class 'float'>
140.2203596700197
<class 'float'>
89.69886948160305
<class 'float'>
98.44194245184163
<class 'float'>
100.66479694162867
<class 'float'>
104.73678078683484
<class 'float'>
88.70584801253955
<class 'float'>
122.4498469731638
<class 'float'>
134.93000480048144
<class 'float'>
106.51648059666732
<class 'float'>
140.24945649502234
<class 'float'>
9.593548483797768
<class 'float'>
88.752916031775
<class 'float'>
-17.484808625840518
<class 'float'>
88.78765202333234
<class 'float'>
25.489172788192835
<class 'float'>
119.83678710493068
<class 'float'>
43.37016332777911
<class 'float'>
97.14635826705297
<class 'float'>
59.41339071497631
<class 'float'>
122.4206382431396
<class 'float'>
106.5546014819741
<class 'float'>
104.46042843784834
<class 'float'>
122.38781965891148
<class 'float'>
98.28284994494975
<class 'float'>
140.0952618338786
<class 'float'>
88.78033089683527
<class 'float'>
122.43052134794368
<class 'float'>
122.39086186851306
<class 'float'>
88.75876033533088
<class 'float'>
63.602160319059536
<class 'float'>
88.78292318552789
<class 'float'>
6.074064764814929
<class 'float'>
31.653582303172264
<class 'float'>
-25.864072533814724
<class 'float'>
50.830779958925724
<class 'float'>
104.64653891554903
<class 'float'>
27.630641755336036
<class 'float'>
129.18536795551094
<class 'float'>
98.28860216693735
<class 'float'>
-16.480414200298686
<class 'float'>
87.16559908849918
<class 'float'>
-3.5009023767258256
<class 'float'>
135.23049294620986
<class 'float'>
5.420081382588088
<class 'float'>
63.09722621248143
<class 'float'>
117.37061312734672
<class 'float'>
88.81088005306536
<class 'float'>
-8.123008682630328
<class 'float'>
137.13603059276576
<class 'float'>
41.79081573426824
<class 'float'>
6.382348000752736
<class 'float'>
80.86395071066872
<class 'float'>
106.60714081023193
<class 'float'>
-27.88226377644464
<class 'float'>
31.8345313845469
<class 'float'>
82.94656830219054
<class 'float'>
122.45192405191578
<class 'float'>
1.3348458035443325
<class 'float'>
80.4852149333426
<class 'float'>
106.58035536095664
<class 'float'>
86.27037517486643
<class 'float'>
88.83125470459383
<class 'float'>
113.12850349579544
<class 'float'>
85.48108012409584
<class 'float'>
9.598059330231003
<class 'float'>
154.47706509391625
<class 'float'>
45.52339072401888
<class 'float'>
186.70558868965398
<class 'float'>
104.62027339569315
<class 'float'>
29.674093118052717
<class 'float'>
162.7847287090206
<class 'float'>
98.20047477170554
<class 'float'>
88.8527949557126
<class 'float'>
9.817022778810092
<class 'float'>
-8.057764332160858
<class 'float'>
106.60043861258752
<class 'float'>
124.39928117151436
<class 'float'>
82.66575335438183
<class 'float'>
179.42590646632954
<class 'float'>
39.24330302919225
<class 'float'>
122.4597778443691
<class 'float'>
122.45948644447152
<class 'float'>
122.48349077365718
<class 'float'>
21.323672172042073
<class 'float'>
27.443106195632897
<class 'float'>
41.690341156165495
<class 'float'>
1.3691376928645762
<class 'float'>
117.42650516989822
<class 'float'>
140.27682704491556
<class 'float'>
80.57583901784972
<class 'float'>
114.89361284223786
<class 'float'>
80.53138892943203
<class 'float'>
80.57608962042934
<class 'float'>
88.84645059740889
<class 'float'>
41.36669998855218
<class 'float'>
29.819039908849255
<class 'float'>
88.86987212679938
<class 'float'>
88.87655450099051
<class 'float'>
88.83981950746806
<class 'float'>
124.39707818295945
<class 'float'>
104.65076659941248
<class 'float'>
122.3274556315597
<class 'float'>
85.4962608617181
<class 'float'>
3.276651169896063
<class 'float'>
80.55122157848326
<class 'float'>
168.68515253934103
<class 'float'>
-2.573893650051798
<class 'float'>
88.81335110021551
<class 'float'>
88.8407298362183
<class 'float'>
-14.465741470150505
<class 'float'>
32.32179235085707
<class 'float'>
122.50945912616187
<class 'float'>
88.87488302798046
<class 'float'>
126.27397284697662
<class 'float'>
122.52185759328312
<class 'float'>
163.81164007412062
<class 'float'>
-9.964698527246227
<class 'float'>
152.90128450432306
<class 'float'>
97.33931622850507
<class 'float'>
98.2919940297701
<class 'float'>
106.59857363992002
<class 'float'>
-1.6916788221309467
<class 'float'>
88.83934976310584
<class 'float'>
106.61007226522337
<class 'float'>
122.50994517612831
<class 'float'>
122.35168791508305
<class 'float'>
-23.96520782173108
<class 'float'>
73.06755246862726
<class 'float'>
104.69412334635481
<class 'float'>
61.832134910716874
<class 'float'>
106.6608981727418
<class 'float'>
66.03378221680546
<class 'float'>
187.11542232253944
<class 'float'>
19.173697495132945
<class 'float'>
106.63048771406977
<class 'float'>
187.43286716592806
<class 'float'>
104.75680571851727
<class 'float'>
35.190004457345694
<class 'float'>
88.87203080018728
<class 'float'>
85.543068941853
<class 'float'>
25.651771363761785
<class 'float'>
98.3258511533742
<class 'float'>
95.8803815854377
<class 'float'>
101.39280131353529
<class 'float'>
83.90991206877341
<class 'float'>
140.23029751030825
<class 'float'>
98.84181142594258
<class 'float'>
77.26131190807071
<class 'float'>
-25.839093803873386
<class 'float'>
27.50852537271793
<class 'float'>
88.90475263458667
<class 'float'>
55.430162007631274
<class 'float'>
-23.943539359986556
<class 'float'>
5.305000231638339
<class 'float'>
106.65502937747218
<class 'float'>
-25.5749667974185
<class 'float'>
55.398971640058065
<class 'float'>
12.189006254497437
<class 'float'>
25.691293296045718
<class 'float'>
88.92822544822747
<class 'float'>
88.84244907562957
<class 'float'>
140.2769260955671
<class 'float'>
106.64392472056701
<class 'float'>
181.93382532193039
<class 'float'>
64.07458026990659
<class 'float'>
106.6797190749536
<class 'float'>
80.61751495526107
<class 'float'>
-7.944264238589511
<class 'float'>
88.89793271324885
<class 'float'>
88.94600781106328
<class 'float'>
122.52353603537644
<class 'float'>
106.69506767010816
<class 'float'>
122.53982526966686
<class 'float'>
80.60872634234374
<class 'float'>
57.195635730745
<class 'float'>
106.73574471505009
<class 'float'>
106.67561383426228
<class 'float'>
154.88164902558535
<class 'float'>
25.5248435335993
<class 'float'>
87.02365276270838
<class 'float'>
7.938614246275969
<class 'float'>
9.71851337443777
<class 'float'>
59.77502915891626
<class 'float'>
88.92955538750104
<class 'float'>
25.646598423720267
<class 'float'>
50.062555567333995
<class 'float'>
79.6332972247912
<class 'float'>
122.5601999211953
<class 'float'>
106.70923551047959
<class 'float'>
88.93793020856688
<class 'float'>
83.00553703462221
<class 'float'>
104.17418563569879
<class 'float'>
106.7058203063445
<class 'float'>
88.99547928759439
<class 'float'>
105.0073992593422
<class 'float'>
187.48947046569862
<class 'float'>
106.74964679764908
<class 'float'>
7.811072747560282
<class 'float'>
37.25116707519463
<class 'float'>
79.56478477414551
<class 'float'>
73.02061295071353
<class 'float'>
29.85159036786728
<class 'float'>
27.5481964894923
<class 'float'>
88.91855329909646
<class 'float'>
88.93243440783077
<class 'float'>
88.90897208112231
<class 'float'>
5.8241912133812646
<class 'float'>
41.23636392333788
<class 'float'>
106.59655129665255
<class 'float'>
106.76722984215557
<class 'float'>
80.60581816203981
<class 'float'>
153.22888232923708
<class 'float'>
80.58048971225244
<class 'float'>
80.28718078825058
<class 'float'>
46.58287003065941
<class 'float'>
-8.889682774885529
<class 'float'>
80.66818349217952
<class 'float'>
88.9452932827933
<class 'float'>
88.94545180380466
<class 'float'>
38.368766883239516
<class 'float'>
98.37166846053435
<class 'float'>
71.59322712694447
<class 'float'>
60.80700435325757
<class 'float'>
122.64261819258029
<class 'float'>
9.779095326545907
<class 'float'>
108.89437261311659
<class 'float'>
46.03822977277105
<class 'float'>
45.70481020179963
<class 'float'>
140.26527591833567
<class 'float'>
54.583411335836225
<class 'float'>
-7.967121641226726
<class 'float'>
119.25818679447741
<class 'float'>
71.11780754105816
<class 'float'>
96.66912541832616
<class 'float'>
122.6214159573489
<class 'float'>
25.714747436644632
<class 'float'>
88.95797848155166
<class 'float'>
73.0473995504002
<class 'float'>
88.97876692493158
<class 'float'>
103.34950650454402
<class 'float'>
27.523625666115667
<class 'float'>
81.22476157090577
<class 'float'>
88.98210053443073
<class 'float'>
25.692394757015737
<class 'float'>
43.45749324777142
<class 'float'>
106.70252397631424
<class 'float'>
116.21946613564023
<class 'float'>
122.5712859050586
<class 'float'>
-7.983614862106933
<class 'float'>
41.800023891094035
<class 'float'>
84.80512032884585
<class 'float'>
85.62291238056096
<class 'float'>
122.64136633009356
<class 'float'>
131.98936318810925
<class 'float'>
122.65788052483846
<class 'float'>
-11.963350888160148
<class 'float'>
146.7572518695635
<class 'float'>
106.76786507661244
<class 'float'>
79.5413254669186
<class 'float'>
106.74366142909744
<class 'float'>
-13.851500338128204
<class 'float'>
41.8444436691261
<class 'float'>
98.47640910116259
<class 'float'>
63.41471760524503
<class 'float'>
122.65811597222527
<class 'float'>
89.01251681177462
<class 'float'>
96.67413165124675
<class 'float'>
180.647260652074
<class 'float'>
97.51584252879816
<class 'float'>
45.52902515569822
<class 'float'>
79.70735231245406
<class 'float'>
88.96892576785687