In [1]:
import pandas as pd

In [5]:
df1 = pd.read_csv('lds1.csv')
df1

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date
Deccan_Sporting,931,839.80,615,Pvt,154,Hyd,1,SPRT,Services,Mar 1943
Kolkata_FMCG,925,874.40,676,Pub,1379,Kol,0,KFMC,Goods,Jan 1920
NCR_Leagles,931,863.50,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960
Bangalore_Systems,900,881.60,650,Gov,1361,Blr,0,BSYS,Services,Apr 1950
Chennai_Chemicals,966,863.20,608,Pub,1656,Che,1,CHEM,Goods,Aug 1928
Indi_Services,954,733.00,609,Gov,13023,NCR,0,INDI,Services,Mar 1920
Bangalore_Breweries,966,805.00,899,Pvt,119,Blr,1,BREW,Goods,Oct 1971
Bombay_Finance,899,917.00,674,Pub,1443,Mum,0,BFIN,Services,Apr 1925
Chennai_Shipping,992,821.00,665,Pub,899,Che,1,SHIP,Goods,Nov 1930
Eastern_Estates,945,834.23,789,Pvt,1873,Kol,1,EEST,Goods,Jan 1994
Central_Services,934,824.00,689,Gov,1573,NCR,1,CSRV,Services,Jun 1974

# sorting

In [16]:
temp = df1[df1['Vol'] > 950]


temp = df1.groupby("Sector").agg({"Rev": "mean", "Exp": "sum"})

temp

               Rev   Exp
Sector
Gov     812.866667  1948
Pub     867.820000  3228
Pvt     826.343333  2303

In [ ]:
temp = df1.groupby("sector").agg({"Rev": "avg", "Exp": "sum"})

In [17]:
help(pd.set_option)

Help on CallableDynamicDoc in module pandas._config.config:

<pandas._config.config.CallableDynamicDoc object>
    set_option(pat, value)

    Sets the value of the specified option.

    Available options:

    - compute.[use_bottleneck, use_numba, use_numexpr]
    - display.[chop_threshold, colheader_justify, date_dayfirst, date_yearfirst,
      encoding, expand_frame_repr, float_format]
    - display.html.[border, table_schema, use_mathjax]
    - display.[large_repr, max_categories, max_columns, max_colwidth, max_dir_items,
      max_info_columns, max_info_rows, max_rows, max_seq_items, memory_usage,
      min_rows, multi_sparse, notebook_repr_html, pprint_nest_depth, precision,
      show_dimensions]
    - display.unicode.[ambiguous_as_wide, east_asian_width]
    - display.[width]
    - future.[infer_string, no_silent_downcasting]
    - io.excel.ods.[reader, writer]
    - io.excel.xls.[reader]
    - io.excel.xlsb.[reader]
    - io.excel.xlsm.[reader, writer]
    - io.excel.xlsx.[reader, writer]
    - io.hdf.[default_format, dropna_table]
    - io.parquet.[engine]
    - io.sql.[engine]
    - mode.[chained_assignment, copy_on_write, data_manager, sim_interactive,
      string_storage, use_inf_as_na]
    - plotting.[backend]
    - plotting.matplotlib.[register_converters]
    - styler.format.[decimal, escape, formatter, na_rep, precision, thousands]
    - styler.html.[mathjax]
    - styler.latex.[environment, hrules, multicol_align, multirow_align]
    - styler.render.[encoding, max_columns, max_elements, max_rows, repr]
    - styler.sparse.[columns, index]

    Parameters
    ----------
    pat : str
        Regexp which should match a single option.
        Note: partial matches are supported for convenience, but unless you use the
        full option name (e.g. x.y.z.option_name), your code may break in future
        versions if new options with similar names are introduced.
    value : object
        New value of option.

    Returns
    -------
    None

    Raises
    ------
    OptionError if no such option exists

    Notes
    -----
    Please reference the :ref:`User Guide <options>` for more information.

    The available options with its descriptions:

    compute.use_bottleneck : bool
        Use the bottleneck library to accelerate if it is installed,
        the default is True
        Valid values: False,True
        [default: True] [currently: True]
    compute.use_numba : bool
        Use the numba engine option for select operations if it is installed,
        the default is False
        Valid values: False,True
        [default: False] [currently: False]
    compute.use_numexpr : bool
        Use the numexpr library to accelerate computation if it is installed,
        the default is True
        Valid values: False,True
        [default: True] [currently: True]
    display.chop_threshold : float or None
        if set to a float value, all float values smaller than the given threshold
        will be displayed as exactly 0 by repr and friends.
        [default: None] [currently: None]
    display.colheader_justify : 'left'/'right'
        Controls the justification of column headers. used by DataFrameFormatter.
        [default: right] [currently: right]
    display.date_dayfirst : boolean
        When True, prints and parses dates with the day first, eg 20/01/2005
        [default: False] [currently: False]
    display.date_yearfirst : boolean
        When True, prints and parses dates with the year first, eg 2005/01/20
        [default: False] [currently: False]
    display.encoding : str/unicode
        Defaults to the detected encoding of the console.
        Specifies the encoding to be used for strings returned by to_string,
        these are generally strings meant to be displayed on the console.
        [default: UTF-8] [currently: UTF-8]
    display.expand_frame_repr : boolean
        Whether to print out the full DataFrame repr for wide DataFrames across
        multiple lines, `max_columns` is still respected, but the output will
        wrap-around across multiple "pages" if its width exceeds `display.width`.
        [default: True] [currently: True]
    display.float_format : callable
        The callable should accept a floating point number and return
        a string with the desired format of the number. This is used
        in some places like SeriesFormatter.
        See formats.format.EngFormatter for an example.
        [default: None] [currently: None]
    display.html.border : int
        A ``border=value`` attribute is inserted in the ``<table>`` tag
        for the DataFrame HTML repr.
        [default: 1] [currently: 1]
    display.html.table_schema : boolean
        Whether to publish a Table Schema representation for frontends
        that support it.
        (default: False)
        [default: False] [currently: False]
    display.html.use_mathjax : boolean
        When True, Jupyter notebook will process table contents using MathJax,
        rendering mathematical expressions enclosed by the dollar symbol.
        (default: True)
        [default: True] [currently: True]
    display.large_repr : 'truncate'/'info'
        For DataFrames exceeding max_rows/max_cols, the repr (and HTML repr) can
        show a truncated table, or switch to the view from
        df.info() (the behaviour in earlier versions of pandas).
        [default: truncate] [currently: truncate]
    display.max_categories : int
        This sets the maximum number of categories pandas should output when
        printing out a `Categorical` or a Series of dtype "category".
        [default: 8] [currently: 8]
    display.max_columns : int
        If max_cols is exceeded, switch to truncate view. Depending on
        `large_repr`, objects are either centrally truncated or printed as
        a summary view. 'None' value means unlimited.

        In case python/IPython is running in a terminal and `large_repr`
        equals 'truncate' this can be set to 0 or None and pandas will auto-detect
        the width of the terminal and print a truncated object which fits
        the screen width. The IPython notebook, IPython qtconsole, or IDLE
        do not run in a terminal and hence it is not possible to do
        correct auto-detection and defaults to 20.
        [default: 20] [currently: 20]
    display.max_colwidth : int or None
        The maximum width in characters of a column in the repr of
        a pandas data structure. When the column overflows, a "..."
        placeholder is embedded in the output. A 'None' value means unlimited.
        [default: 50] [currently: 50]
    display.max_dir_items : int
        The number of items that will be added to `dir(...)`. 'None' value means
        unlimited. Because dir is cached, changing this option will not immediately
        affect already existing dataframes until a column is deleted or added.

        This is for instance used to suggest columns from a dataframe to tab
        completion.
        [default: 100] [currently: 100]
    display.max_info_columns : int
        max_info_columns is used in DataFrame.info method to decide if
        per column information will be printed.
        [default: 100] [currently: 100]
    display.max_info_rows : int
        df.info() will usually show null-counts for each column.
        For large frames this can be quite slow. max_info_rows and max_info_cols
        limit this null check only to frames with smaller dimensions than
        specified.
        [default: 1690785] [currently: 1690785]
    display.max_rows : int
        If max_rows is exceeded, switch to truncate view. Depending on
        `large_repr`, objects are either centrally truncated or printed as
        a summary view. 'None' value means unlimited.

        In case python/IPython is running in a terminal and `large_repr`
        equals 'truncate' this can be set to 0 and pandas will auto-detect
        the height of the terminal and print a truncated object which fits
        the screen height. The IPython notebook, IPython qtconsole, or
        IDLE do not run in a terminal and hence it is not possible to do
        correct auto-detection.
        [default: 60] [currently: 60]
    display.max_seq_items : int or None
        When pretty-printing a long sequence, no more then `max_seq_items`
        will be printed. If items are omitted, they will be denoted by the
        addition of "..." to the resulting string.

        If set to None, the number of items to be printed is unlimited.
        [default: 100] [currently: 100]
    display.memory_usage : bool, string or None
        This specifies if the memory usage of a DataFrame should be displayed when
        df.info() is called. Valid values True,False,'deep'
        [default: True] [currently: True]
    display.min_rows : int
        The numbers of rows to show in a truncated view (when `max_rows` is
        exceeded). Ignored when `max_rows` is set to None or 0. When set to
        None, follows the value of `max_rows`.
        [default: 10] [currently: 10]
    display.multi_sparse : boolean
        "sparsify" MultiIndex display (don't display repeated
        elements in outer levels within groups)
        [default: True] [currently: True]
    display.notebook_repr_html : boolean
        When True, IPython notebook will use html representation for
        pandas objects (if it is available).
        [default: True] [currently: True]
    display.pprint_nest_depth : int
        Controls the number of nested levels to process when pretty-printing
        [default: 3] [currently: 3]
    display.precision : int
        Floating point output precision in terms of number of places after the
        decimal, for regular formatting as well as scientific notation. Similar
        to ``precision`` in :meth:`numpy.set_printoptions`.
        [default: 6] [currently: 6]
    display.show_dimensions : boolean or 'truncate'
        Whether to print out dimensions at the end of DataFrame repr.
        If 'truncate' is specified, only print out the dimensions if the
        frame is truncated (e.g. not display all rows and/or columns)
        [default: truncate] [currently: truncate]
    display.unicode.ambiguous_as_wide : boolean
        Whether to use the Unicode East Asian Width to calculate the display text
        width.
        Enabling this may affect to the performance (default: False)
        [default: False] [currently: False]
    display.unicode.east_asian_width : boolean
        Whether to use the Unicode East Asian Width to calculate the display text
        width.
        Enabling this may affect to the performance (default: False)
        [default: False] [currently: False]
    display.width : int
        Width of the display in characters. In case python/IPython is running in
        a terminal this can be set to None and pandas will correctly auto-detect
        the width.
        Note that the IPython notebook, IPython qtconsole, or IDLE do not run in a
        terminal and hence it is not possible to correctly detect the width.
        [default: 80] [currently: 80]
    future.infer_string Whether to infer sequence of str objects as pyarrow string dtype, which will be the default in pandas 3.0 (at which point this option will be deprecated).
        [default: False] [currently: False]
    future.no_silent_downcasting Whether to opt-in to the future behavior which will *not* silently downcast results from Series and DataFrame `where`, `mask`, and `clip` methods. Silent downcasting will be removed in pandas 3.0 (at which point this option will be deprecated).
        [default: False] [currently: False]
    io.excel.ods.reader : string
        The default Excel reader engine for 'ods' files. Available options:
        auto, odf, calamine.
        [default: auto] [currently: auto]
    io.excel.ods.writer : string
        The default Excel writer engine for 'ods' files. Available options:
        auto, odf.
        [default: auto] [currently: auto]
    io.excel.xls.reader : string
        The default Excel reader engine for 'xls' files. Available options:
        auto, xlrd, calamine.
        [default: auto] [currently: auto]
    io.excel.xlsb.reader : string
        The default Excel reader engine for 'xlsb' files. Available options:
        auto, pyxlsb, calamine.
        [default: auto] [currently: auto]
    io.excel.xlsm.reader : string
        The default Excel reader engine for 'xlsm' files. Available options:
        auto, xlrd, openpyxl, calamine.
        [default: auto] [currently: auto]
    io.excel.xlsm.writer : string
        The default Excel writer engine for 'xlsm' files. Available options:
        auto, openpyxl.
        [default: auto] [currently: auto]
    io.excel.xlsx.reader : string
        The default Excel reader engine for 'xlsx' files. Available options:
        auto, xlrd, openpyxl, calamine.
        [default: auto] [currently: auto]
    io.excel.xlsx.writer : string
        The default Excel writer engine for 'xlsx' files. Available options:
        auto, openpyxl, xlsxwriter.
        [default: auto] [currently: auto]
    io.hdf.default_format : format
        default format writing format, if None, then
        put will default to 'fixed' and append will default to 'table'
        [default: None] [currently: None]
    io.hdf.dropna_table : boolean
        drop ALL nan rows when appending to a table
        [default: False] [currently: False]
    io.parquet.engine : string
        The default parquet reader/writer engine. Available options:
        'auto', 'pyarrow', 'fastparquet', the default is 'auto'
        [default: auto] [currently: auto]
    io.sql.engine : string
        The default sql reader/writer engine. Available options:
        'auto', 'sqlalchemy', the default is 'auto'
        [default: auto] [currently: auto]
    mode.chained_assignment : string
        Raise an exception, warn, or no action if trying to use chained assignment,
        The default is warn
        [default: warn] [currently: warn]
    mode.copy_on_write : bool
        Use new copy-view behaviour using Copy-on-Write. Defaults to False,
        unless overridden by the 'PANDAS_COPY_ON_WRITE' environment variable
        (if set to "1" for True, needs to be set before pandas is imported).
        [default: False] [currently: False]
    mode.data_manager : string
        Internal data manager type; can be "block" or "array". Defaults to "block",
        unless overridden by the 'PANDAS_DATA_MANAGER' environment variable (needs
        to be set before pandas is imported).
        [default: block] [currently: block]
        (Deprecated, use `` instead.)
    mode.sim_interactive : boolean
        Whether to simulate interactive mode for purposes of testing
        [default: False] [currently: False]
    mode.string_storage : string
        The default storage for StringDtype. This option is ignored if
        ``future.infer_string`` is set to True.
        [default: python] [currently: python]
    mode.use_inf_as_na : boolean
        True means treat None, NaN, INF, -INF as NA (old way),
        False means None and NaN are null, but INF, -INF are not NA
        (new way).

        This option is deprecated in pandas 2.1.0 and will be removed in 3.0.
        [default: False] [currently: False]
        (Deprecated, use `` instead.)
    plotting.backend : str
        The plotting backend to use. The default value is "matplotlib", the
        backend provided with pandas. Other backends can be specified by
        providing the name of the module that implements the backend.
        [default: matplotlib] [currently: matplotlib]
    plotting.matplotlib.register_converters : bool or 'auto'.
        Whether to register converters with matplotlib's units registry for
        dates, times, datetimes, and Periods. Toggling to False will remove
        the converters, restoring any converters that pandas overwrote.
        [default: auto] [currently: auto]
    styler.format.decimal : str
        The character representation for the decimal separator for floats and complex.
        [default: .] [currently: .]
    styler.format.escape : str, optional
        Whether to escape certain characters according to the given context; html or latex.
        [default: None] [currently: None]
    styler.format.formatter : str, callable, dict, optional
        A formatter object to be used as default within ``Styler.format``.
        [default: None] [currently: None]
    styler.format.na_rep : str, optional
        The string representation for values identified as missing.
        [default: None] [currently: None]
    styler.format.precision : int
        The precision for floats and complex numbers.
        [default: 6] [currently: 6]
    styler.format.thousands : str, optional
        The character representation for thousands separator for floats, int and complex.
        [default: None] [currently: None]
    styler.html.mathjax : bool
        If False will render special CSS classes to table attributes that indicate Mathjax
        will not be used in Jupyter Notebook.
        [default: True] [currently: True]
    styler.latex.environment : str
        The environment to replace ``\begin{table}``. If "longtable" is used results
        in a specific longtable environment format.
        [default: None] [currently: None]
    styler.latex.hrules : bool
        Whether to add horizontal rules on top and bottom and below the headers.
        [default: False] [currently: False]
    styler.latex.multicol_align : {"r", "c", "l", "naive-l", "naive-r"}
        The specifier for horizontal alignment of sparsified LaTeX multicolumns. Pipe
        decorators can also be added to non-naive values to draw vertical
        rules, e.g. "\|r" will draw a rule on the left side of right aligned merged cells.
        [default: r] [currently: r]
    styler.latex.multirow_align : {"c", "t", "b"}
        The specifier for vertical alignment of sparsified LaTeX multirows.
        [default: c] [currently: c]
    styler.render.encoding : str
        The encoding used for output HTML and LaTeX files.
        [default: utf-8] [currently: utf-8]
    styler.render.max_columns : int, optional
        The maximum number of columns that will be rendered. May still be reduced to
        satisfy ``max_elements``, which takes precedence.
        [default: None] [currently: None]
    styler.render.max_elements : int
        The maximum number of data-cell (<td>) elements that will be rendered before
        trimming will occur over columns, rows or both if needed.
        [default: 262144] [currently: 262144]
    styler.render.max_rows : int, optional
        The maximum number of rows that will be rendered. May still be reduced to
        satisfy ``max_elements``, which takes precedence.
        [default: None] [currently: None]
    styler.render.repr : str
        Determine which output to use in Jupyter Notebook in {"html", "latex"}.
        [default: html] [currently: html]
    styler.sparse.columns : bool
        Whether to sparsify the display of hierarchical columns. Setting to False will
        display each explicit level element in a hierarchical key for each column.
        [default: True] [currently: True]
    styler.sparse.index : bool
        Whether to sparsify the display of a hierarchical index. Setting to False will
        display each explicit level element in a hierarchical key for each row.
        [default: True] [currently: True]

    Examples
    --------
    >>> pd.set_option('display.max_columns', 4)
    >>> df = pd.DataFrame([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
    >>> df
       0  1  ...  3   4
    0  1  2  ...  4   5
    1  6  7  ...  9  10
    [2 rows x 5 columns]
    >>> pd.reset_option('display.max_columns')

In [ ]:
class point():
    def __init__(self, px=0, py=0):
        self.x = px
        self.y = py

In [2]:
s = " \""

In [3]:
s

' "'

In [5]:
s = '\"'

In [6]:
s

'"'

In [8]:
import pandas as pd

In [11]:
df = pd.read_csv('201801_Punctuality_Statistics_Full_Analysis.csv')

In [17]:
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3208 entries, 0 to 3207
Data columns (total 25 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   run_date                                            3208 non-null   object
 1   reporting_period                                    3208 non-null   int64
 2   reporting_airport                                   3208 non-null   object
 3   origin_destination_country                          3208 non-null   object
 4   origin_destination                                  3208 non-null   object
 5   airline_name                                        3208 non-null   object
 6   scheduled_charter                                   3208 non-null   object
 7   number_flights_matched                              3208 non-null   int64
 8   actual_flights_unmatched                            3208 non-null   int64
 9   number_flights_cancelled                            3208 non-null   int64
 10  flights_more_than_15_minutes_early_percent          3208 non-null   float64
 11  flights_15_minutes_early_to_1_minute_early_percent  3208 non-null   float64
 12  flights_0_to_15_minutes_late_percent                3208 non-null   float64
 13  flights_between_16_and_30_minutes_late_percent      3208 non-null   float64
 14  flights_between_31_and_60_minutes_late_percent      3208 non-null   float64
 15  flights_between_61_and_120_minutes_late_percent     3208 non-null   float64
 16  flights_between_121_and_180_minutes_late_percent    3208 non-null   float64
 17  flights_between_181_and_360_minutes_late_percent    3208 non-null   float64
 18  flights_more_than_360_minutes_late_percent          3208 non-null   float64
 19  flights_unmatched_percent                           3208 non-null   float64
 20  flights_cancelled_percent                           3208 non-null   float64
 21  average_delay_mins                                  3208 non-null   float64
 22  previous_year_month_flights_matched                 3208 non-null   int64
 23  previous_year_month_early_to_15_mins_late_percent   3208 non-null   float64
 24  previous_year_month_average_delay                   3208 non-null   float64
dtypes: float64(14), int64(5), object(6)
memory usage: 626.7+ KB

In [24]:
df[df.origin_destination_country == 'VIETNAM']
# df

,run_date,reporting_period,reporting_airport,origin_destination_country,origin_destination,airline_name,scheduled_charter,number_flights_matched,actual_flights_unmatched,number_flights_cancelled,...,flights_between_61_and_120_minutes_late_percent,flights_between_121_and_180_minutes_late_percent,flights_between_181_and_360_minutes_late_percent,flights_more_than_360_minutes_late_percent,flights_unmatched_percent,flights_cancelled_percent,average_delay_mins,previous_year_month_flights_matched,previous_year_month_early_to_15_mins_late_percent,previous_year_month_average_delay
1398,30/04/2018 13:48,201801,GATWICK,VIETNAM,PHU QUOC INTERNATIONAL,TUI AIRWAYS LTD,C,9,0,0,...,11.111111,0.0,0.0,0.0,0.0,0.0,25.888889,0,0.000000,0.000000
1858,30/04/2018 13:48,201801,HEATHROW,VIETNAM,HANOI,VIETNAM AIRLINES,S,34,0,0,...,0.000000,0.0,0.0,0.0,0.0,0.0,6.558824,36,63.888889,16.277778
1859,30/04/2018 13:48,201801,HEATHROW,VIETNAM,HO CHI MINH CITY,VIETNAM AIRLINES,S,28,0,0,...,3.571429,0.0,0.0,0.0,0.0,0.0,12.321429,26,76.923077,8.653846

In [25]:
df.origin_destination_country.value_counts()

origin_destination_country
UNITED KINGDOM            619
SPAIN                     268
FRANCE                    249
SPAIN(CANARY ISLANDS)     246
ITALY                     167
                         ...
ANGOLA                      1
ETHIOPIA                    1
KAZAKHSTAN                  1
UZBEKISTAN                  1
REPUBLIC OF MONTENEGRO      1
Name: count, Length: 118, dtype: int64

In [28]:
df.airline_name.unique()

array(['WIZZ AIR', 'FLYBE LTD', 'BMI REGIONAL', 'EASTERN AIRWAYS',
       'LOGANAIR LTD', 'EASYJET AIRLINE COMPANY LTD',
       'BRITISH AIRWAYS PLC', 'EASYJET SWITZERLAND', 'SAS', 'AIR FRANCE',
       'LUFTHANSA', 'FLUGFELAG ISLANDS(AIR ICELAND)', 'AER LINGUS', 'KLM',
       'KLM CITYHOPPER', 'WIDEROE FLYVESELSKAP A/S', 'RYANAIR',
       'TUI AIRWAYS LTD', 'AIR HAMBURG', 'SAXONAIR CHARTER LTD',
       'VANAIR EUROPE AS', 'AIR ALSIE', 'NETJETS TRANSPORTES AEREOS',
       'BRUSSELS AIRLINES', 'TAG AVIATION (UK) LTD',
       'THOMAS COOK AIRLINES LTD', 'JET2.COM LTD', 'VISTAJET LTD MALTA',
       'UNITED AIRLINES', 'NORWEGIAN AIR INTERNATIONAL',
       'GERMANIA FLUGGESELLSCHAFT', 'EUROPE AIRPOST',
       'CSA CZECH AIRLINES', 'BLUE AIR TRANSPORT AERIAN', 'Unknown',
       'TURKMENISTAN AIRLINES', 'AIR INDIA', 'PAKISTAN INTL AIRLINES',
       'QATAR AIRWAYS', 'EMIRATES', 'ENTER AIR', 'MONARCH AIRLINES',
       'EDELWEISS AIR', 'CELLO AVIATION LTD', 'AMERICAN AIRLINES',
       'AUSTRIAN AIRLINES', 'EUROWINGS LUFTVERKEHRS', 'COBALT',
       'TITAN AIRWAYS LTD', 'ADRIA AIRWAYS', 'VUELING AIRLINES',
       'GERMANWINGS', 'AIRTANKER SERVICES LTD', 'SMALL PLANET AIRLINES',
       'ICELANDAIR', 'STOBART AIR', 'CARPATAIR', 'CONDOR',
       'IBERIA EXPRESS', 'CITY JET', 'SWISS AIRLINES',
       'FREEBIRD AIRLINES', 'THY TURKISH AIRLINES', 'GAINJET AVIATION',
       'MALETH AERO', 'JOTA AVIATION LTD', 'AURIGNY AIR SERVICES',
       'AERO4M', 'WOW AIR', 'PAN EUROPEAN AIR SERVICE',
       'THOMAS COOK BELGIUM', 'SIAVIA', 'GAMA AVIATION (UK) LTD',
       'FAI FLIGHT- AMBULANCE SERVICE', 'ETIHAD AIRWAYS',
       'BA CITYFLYER LTD', 'DELTA AIRLINES', 'NORWEGIAN AIR SHUTTLE',
       'ATLANTIC AIRWAYS', 'FINNAIR', 'SMARTWINGS', 'TRANSAVIA FRANCE',
       'AEGEAN AIRLINES', 'AIR TRANSAT', 'BLUE ISLANDS LIMITED',
       'VOLOTEA', 'WEST JET AIRLINES', 'VIRGIN ATLANTIC AIRWAYS LTD',
       'RWANDAIR EXPRESS', 'SILK WAY AIRLINES',
       'BELAVIA (BELARUSSIAN AIRLINES)', 'ABS JET', 'GEORGIAN AIRWAYS',
       'ALBA STAR', 'AIR BALTIC', 'AEROFLOT',
       'UKRAINE INTERNATIONAL AIRLINES', 'TIANJIN AIRLINES',
       'CATHAY PACIFIC AIRWAYS', 'NORWEGIAN AIR UK LTD', 'CHINA AIRLINES',
       'IRAQI AIRWAYS', 'ROYAL AIR MAROC', 'AIR ARABIA MAROC',
       'AIR X CHARTER', 'TUNISAIR', 'MED-VIEW AIRLINE', 'LUXAVIATION',
       'GERMANIA FLUG', 'ALBA SERVIZI TRASPORTI', 'AIR MALTA',
       'AIR PORTUGAL', 'AIR EUROPA', 'AIR NOSTRUM', 'DC AVIATION',
       'PEGASUS AIRLINES', 'QANTAS', 'AIR NEW ZEALAND LTD', 'AIR CANADA',
       'AEROMEXICO', 'ETHIOPIAN AIRLINES', 'KENYA AIRWAYS',
       'AZERBAIJAN AIRLINES (AZAL)', 'BULGARIA AIR', 'AIR ASTANA',
       'LOT-POLISH AIRLINES', 'TAROM', 'UZBEKISTAN AIRLINES',
       'ROYAL BRUNEI AIRLINES', 'AIR CHINA', 'CHINA SOUTHERN',
       'CHINA EASTERN AIRLINES', 'HAINAN AIRLINES', 'GARUDA INDONESIA',
       'ALL NIPPON AIRWAYS', 'JAPAN AIRLINES',
       'MALAYSIAN AIRLINES SYSTEM-MAS', 'PHILIPPINE AIRLINES',
       'ASIANA AIRLINES', 'KOREAN AIR', 'SINGAPORE AIRLINES', 'EVA AIR',
       'THAI AIRWAYS INTERNATIONAL', 'VIETNAM AIRLINES',
       'AIR MAURITIUS LTD', 'BIMAN BANGLADESH AIRLINES', 'JET AIRWAYS',
       'SRILANKAN AIRLINES', 'GULF AIR', 'IRAN AIR', 'KUWAIT AIRWAYS',
       'OMAN AIR', 'SAUDI ARABIAN AIRLINES', 'EL AL', 'ROYAL JORDANIAN',
       'MIDDLE EAST AIRLINES (AIR LIBAN S A L)', 'AIR ALGERIE',
       'EGYPT AIR', 'TAM LINHAS AEREAS', 'AVIANCA COLOMBIA',
       'SOUTH AFRICAN AIRWAYS', 'ATLAS AIR  INC', 'ARIK AIR',
       'CROATIA AIRLINES', 'ALITALIA (CAI)', 'AIR SERBIA', 'IBERIA',
       'SUN AIR OF SCANDINAVIA', 'TYROLEAN AIRWAYS', 'LUXAIR',
       'SKY WORK AG', 'AVCON JET AG', 'COMLUX AVIATION (MALTA)',
       'CROSSAIR EUROPE', 'IJM INTERNATIONAL JET MANAGEMENT GMBH',
       'MHS AVIATION GMBH GRUENWALD', 'ARKIA', 'ISRAIR LTD',
       'ITALI AIRLINES', 'KAISER AIR', 'SWISS AIR AMBULANCE',
       'HOP - AIRLINAIR', 'FLYING SERVICE', 'ALBINATI AVIATION',
       'MJET GMBH', 'EUROPEAN AIR TRANSPORT LEIPZIG (EAT)',
       'EXECUTIVE AIRLINES', 'EXECUJET SCANDINAVIA',
       'AIR MOLDOVA INTERNATIONAL', 'TRANSAVIA', 'TUIFLY  (GERMANY)',
       'ATLASJET INTERNATIONAL', 'SHAHEEN AIR', 'THOMAS COOK SCANDANAVIA',
       'AIR CONTRACTORS'], dtype=object)

In [27]:
l=['1,2,3','afds']
','.join(l)

'1,2,3,afds'

In [ ]:
# no of airlines reporting to each airport
# NOTE THAT IT IS ARILINES AND NOT AEROPLANES
df.groupby(['reporting_airport'])['airline_name'].nunique()

reporting_airport
ABERDEEN                       18
BELFAST CITY (GEORGE BEST)     12
BELFAST INTERNATIONAL          13
BIRMINGHAM                     50
BOURNEMOUTH                    10
BRISTOL                        18
CARDIFF WALES                  18
DONCASTER SHEFFIELD             8
DURHAM TEES VALLEY              7
EAST MIDLANDS INTERNATIONAL    13
EDINBURGH                      35
EXETER                          8
GATWICK                        69
GLASGOW                        26
HEATHROW                       84
ISLE OF MAN                     7
JERSEY                          7
LEEDS BRADFORD                 14
LIVERPOOL (JOHN LENNON)        16
LONDON CITY                    14
LUTON                          38
MANCHESTER                     63
NEWCASTLE                      22
SOUTHAMPTON                    12
SOUTHEND                        9
STANSTED                       27
Name: airline_name, dtype: int64

In [33]:
df.columns

Index(['run_date', 'reporting_period', 'reporting_airport',
       'origin_destination_country', 'origin_destination', 'airline_name',
       'scheduled_charter', 'number_flights_matched',
       'actual_flights_unmatched', 'number_flights_cancelled',
       'flights_more_than_15_minutes_early_percent',
       'flights_15_minutes_early_to_1_minute_early_percent',
       'flights_0_to_15_minutes_late_percent',
       'flights_between_16_and_30_minutes_late_percent',
       'flights_between_31_and_60_minutes_late_percent',
       'flights_between_61_and_120_minutes_late_percent',
       'flights_between_121_and_180_minutes_late_percent',
       'flights_between_181_and_360_minutes_late_percent',
       'flights_more_than_360_minutes_late_percent',
       'flights_unmatched_percent', 'flights_cancelled_percent',
       'average_delay_mins', 'previous_year_month_flights_matched',
       'previous_year_month_early_to_15_mins_late_percent',
       'previous_year_month_average_delay'],
      dtype='object')

In [34]:
help(df.merge)

Help on method merge in module pandas.core.frame:

merge(right: 'DataFrame | Series', how: 'MergeHow' = 'inner', on: 'IndexLabel | AnyArrayLike | None' = None, left_on: 'IndexLabel | AnyArrayLike | None' = None, right_on: 'IndexLabel | AnyArrayLike | None' = None, left_index: 'bool' = False, right_index: 'bool' = False, sort: 'bool' = False, suffixes: 'Suffixes' = ('_x', '_y'), copy: 'bool | None' = None, indicator: 'str | bool' = False, validate: 'MergeValidate | None' = None) -> 'DataFrame' method of pandas.core.frame.DataFrame instance
    Merge DataFrame or named Series objects with a database-style join.

    A named Series object is treated as a DataFrame with a single named column.

    The join is done on columns or indexes. If joining columns on
    columns, the DataFrame indexes *will be ignored*. Otherwise if joining indexes
    on indexes or indexes on a column or columns, the index will be passed on.
    When performing a cross merge, no column specifications to merge on are
    allowed.

    .. warning::

        If both key columns contain rows where the key is a null value, those
        rows will be matched against each other. This is different from usual SQL
        join behaviour and can lead to unexpected results.

    Parameters
    ----------
    right : DataFrame or named Series
        Object to merge with.
    how : {'left', 'right', 'outer', 'inner', 'cross'}, default 'inner'
        Type of merge to be performed.

        * left: use only keys from left frame, similar to a SQL left outer join;
          preserve key order.
        * right: use only keys from right frame, similar to a SQL right outer join;
          preserve key order.
        * outer: use union of keys from both frames, similar to a SQL full outer
          join; sort keys lexicographically.
        * inner: use intersection of keys from both frames, similar to a SQL inner
          join; preserve the order of the left keys.
        * cross: creates the cartesian product from both frames, preserves the order
          of the left keys.
    on : label or list
        Column or index level names to join on. These must be found in both
        DataFrames. If `on` is None and not merging on indexes then this defaults
        to the intersection of the columns in both DataFrames.
    left_on : label or list, or array-like
        Column or index level names to join on in the left DataFrame. Can also
        be an array or list of arrays of the length of the left DataFrame.
        These arrays are treated as if they are columns.
    right_on : label or list, or array-like
        Column or index level names to join on in the right DataFrame. Can also
        be an array or list of arrays of the length of the right DataFrame.
        These arrays are treated as if they are columns.
    left_index : bool, default False
        Use the index from the left DataFrame as the join key(s). If it is a
        MultiIndex, the number of keys in the other DataFrame (either the index
        or a number of columns) must match the number of levels.
    right_index : bool, default False
        Use the index from the right DataFrame as the join key. Same caveats as
        left_index.
    sort : bool, default False
        Sort the join keys lexicographically in the result DataFrame. If False,
        the order of the join keys depends on the join type (how keyword).
    suffixes : list-like, default is ("_x", "_y")
        A length-2 sequence where each element is optionally a string
        indicating the suffix to add to overlapping column names in
        `left` and `right` respectively. Pass a value of `None` instead
        of a string to indicate that the column name from `left` or
        `right` should be left as-is, with no suffix. At least one of the
        values must not be None.
    copy : bool, default True
        If False, avoid copy if possible.

        .. note::
            The `copy` keyword will change behavior in pandas 3.0.
            `Copy-on-Write
            <https://pandas.pydata.org/docs/dev/user_guide/copy_on_write.html>`__
            will be enabled by default, which means that all methods with a
            `copy` keyword will use a lazy copy mechanism to defer the copy and
            ignore the `copy` keyword. The `copy` keyword will be removed in a
            future version of pandas.

            You can already get the future behavior and improvements through
            enabling copy on write ``pd.options.mode.copy_on_write = True``
    indicator : bool or str, default False
        If True, adds a column to the output DataFrame called "_merge" with
        information on the source of each row. The column can be given a different
        name by providing a string argument. The column will have a Categorical
        type with the value of "left_only" for observations whose merge key only
        appears in the left DataFrame, "right_only" for observations
        whose merge key only appears in the right DataFrame, and "both"
        if the observation's merge key is found in both DataFrames.

    validate : str, optional
        If specified, checks if merge is of specified type.

        * "one_to_one" or "1:1": check if merge keys are unique in both
          left and right datasets.
        * "one_to_many" or "1:m": check if merge keys are unique in left
          dataset.
        * "many_to_one" or "m:1": check if merge keys are unique in right
          dataset.
        * "many_to_many" or "m:m": allowed, but does not result in checks.

    Returns
    -------
    DataFrame
        A DataFrame of the two merged objects.

    See Also
    --------
    merge_ordered : Merge with optional filling/interpolation.
    merge_asof : Merge on nearest keys.
    DataFrame.join : Similar method using indices.

    Examples
    --------
    >>> df1 = pd.DataFrame({'lkey': ['foo', 'bar', 'baz', 'foo'],
    ...                     'value': [1, 2, 3, 5]})
    >>> df2 = pd.DataFrame({'rkey': ['foo', 'bar', 'baz', 'foo'],
    ...                     'value': [5, 6, 7, 8]})
    >>> df1
        lkey value
    0   foo      1
    1   bar      2
    2   baz      3
    3   foo      5
    >>> df2
        rkey value
    0   foo      5
    1   bar      6
    2   baz      7
    3   foo      8

    Merge df1 and df2 on the lkey and rkey columns. The value columns have
    the default suffixes, _x and _y, appended.

    >>> df1.merge(df2, left_on='lkey', right_on='rkey')
      lkey  value_x rkey  value_y
    0  foo        1  foo        5
    1  foo        1  foo        8
    2  bar        2  bar        6
    3  baz        3  baz        7
    4  foo        5  foo        5
    5  foo        5  foo        8

    Merge DataFrames df1 and df2 with specified left and right suffixes
    appended to any overlapping columns.

    >>> df1.merge(df2, left_on='lkey', right_on='rkey',
    ...           suffixes=('_left', '_right'))
      lkey  value_left rkey  value_right
    0  foo           1  foo            5
    1  foo           1  foo            8
    2  bar           2  bar            6
    3  baz           3  baz            7
    4  foo           5  foo            5
    5  foo           5  foo            8

    Merge DataFrames df1 and df2, but raise an exception if the DataFrames have
    any overlapping columns.

    >>> df1.merge(df2, left_on='lkey', right_on='rkey', suffixes=(False, False))
    Traceback (most recent call last):
    ...
    ValueError: columns overlap but no suffix specified:
        Index(['value'], dtype='object')

    >>> df1 = pd.DataFrame({'a': ['foo', 'bar'], 'b': [1, 2]})
    >>> df2 = pd.DataFrame({'a': ['foo', 'baz'], 'c': [3, 4]})
    >>> df1
          a  b
    0   foo  1
    1   bar  2
    >>> df2
          a  c
    0   foo  3
    1   baz  4

    >>> df1.merge(df2, how='inner', on='a')
          a  b  c
    0   foo  1  3

    >>> df1.merge(df2, how='left', on='a')
          a  b  c
    0   foo  1  3.0
    1   bar  2  NaN

    >>> df1 = pd.DataFrame({'left': ['foo', 'bar']})
    >>> df2 = pd.DataFrame({'right': [7, 8]})
    >>> df1
        left
    0   foo
    1   bar
    >>> df2
        right
    0   7
    1   8

    >>> df1.merge(df2, how='cross')
       left  right
    0   foo      7
    1   foo      8
    2   bar      7
    3   bar      8

In [ ]:
pd.Series()